version: 2
jobs:
  #  ビルド ジョブとテスト ジョブ
  deploy-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: gem install bundler -v 2.1.4
      - run:
          name: バンドル インストール
          command: bundle check || bundle install
      - run:
          name: テストが完了し、ブランチが master である場合は AWS にデプロイ
          command: bundle exec cap production deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
